//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriculturaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicacionFertilizante
    {
        public int IdSiembra { get; set; }
        public int IdFertilizante { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual Fertilizante Fertilizante { get; set; }
        public virtual Siembra Siembra { get; set; }
    }
}
