//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriculturaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cosecha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cosecha()
        {
            this.DetalleEnvios = new HashSet<DetalleEnvio>();
        }
    
        public int IdCosecha { get; set; }
        public int IdSiembra { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal PesoKg { get; set; }
        public string Calidad { get; set; }
    
        public virtual Siembra Siembra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEnvio> DetalleEnvios { get; set; }
    }
}
