//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriculturaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEnvio
    {
        public int IdDetalleEnvio { get; set; }
        public int IdEnvio { get; set; }
        public int IdCosecha { get; set; }
        public decimal PesoKg { get; set; }
    
        public virtual Cosecha Cosecha { get; set; }
        public virtual Envio Envio { get; set; }
    }
}
