//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriculturaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jornada
    {
        public int IdJornada { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Horas { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
