//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriculturaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LecturaSensor
    {
        public int IdLectura { get; set; }
        public int IdSensor { get; set; }
        public System.DateTime FechaHora { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Sensor Sensor { get; set; }
    }
}
