//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriculturaWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgriculturaDBEntities : DbContext
    {
        public AgriculturaDBEntities()
            : base("name=AgriculturaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacen> Almacens { get; set; }
        public virtual DbSet<AplicacionFertilizante> AplicacionFertilizantes { get; set; }
        public virtual DbSet<AplicacionPlaga> AplicacionPlagas { get; set; }
        public virtual DbSet<AsignacionTarea> AsignacionTareas { get; set; }
        public virtual DbSet<Banco> Bancoes { get; set; }
        public virtual DbSet<CategoriaGasto> CategoriaGastoes { get; set; }
        public virtual DbSet<CategoriaIngreso> CategoriaIngresoes { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<ClimaRegistro> ClimaRegistroes { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<Contrato> Contratoes { get; set; }
        public virtual DbSet<Cosecha> Cosechas { get; set; }
        public virtual DbSet<CuentaBancaria> CuentaBancarias { get; set; }
        public virtual DbSet<Cultivo> Cultivos { get; set; }
        public virtual DbSet<DetalleCompra> DetalleCompras { get; set; }
        public virtual DbSet<DetalleEnvio> DetalleEnvios { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVentas { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Envio> Envios { get; set; }
        public virtual DbSet<Fertilizante> Fertilizantes { get; set; }
        public virtual DbSet<Finca> Fincas { get; set; }
        public virtual DbSet<Gasto> Gastoes { get; set; }
        public virtual DbSet<Ingreso> Ingresoes { get; set; }
        public virtual DbSet<Jornada> Jornadas { get; set; }
        public virtual DbSet<LecturaSensor> LecturaSensors { get; set; }
        public virtual DbSet<Lote> Lotes { get; set; }
        public virtual DbSet<Mantenimiento> Mantenimientoes { get; set; }
        public virtual DbSet<Maquinaria> Maquinarias { get; set; }
        public virtual DbSet<MonitoreoSuelo> MonitoreoSueloes { get; set; }
        public virtual DbSet<MovimientoInventario> MovimientoInventarios { get; set; }
        public virtual DbSet<Pago> Pagoes { get; set; }
        public virtual DbSet<Plaga> Plagas { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Riego> Riegoes { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Sensor> Sensors { get; set; }
        public virtual DbSet<Siembra> Siembras { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tarea> Tareas { get; set; }
        public virtual DbSet<Temporada> Temporadas { get; set; }
        public virtual DbSet<Transporte> Transportes { get; set; }
        public virtual DbSet<Tratamiento> Tratamientoes { get; set; }
        public virtual DbSet<Ubicacion> Ubicacions { get; set; }
        public virtual DbSet<UsoMaquinaria> UsoMaquinarias { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Variedad> Variedads { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    }
}
