//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriculturaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int IdPago { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public Nullable<int> IdCompra { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public string Metodo { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual CuentaBancaria CuentaBancaria { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
