//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriculturaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Riego
    {
        public int IdRiego { get; set; }
        public int IdSiembra { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal VolumenLitros { get; set; }
        public string Metodo { get; set; }
    
        public virtual Siembra Siembra { get; set; }
    }
}
