//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriculturaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siembra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siembra()
        {
            this.AplicacionFertilizantes = new HashSet<AplicacionFertilizante>();
            this.AplicacionPlagas = new HashSet<AplicacionPlaga>();
            this.AsignacionTareas = new HashSet<AsignacionTarea>();
            this.Cosechas = new HashSet<Cosecha>();
            this.Gastoes = new HashSet<Gasto>();
            this.Riegoes = new HashSet<Riego>();
            this.UsoMaquinarias = new HashSet<UsoMaquinaria>();
        }
    
        public int IdSiembra { get; set; }
        public int IdLote { get; set; }
        public int IdVariedad { get; set; }
        public int IdTemporada { get; set; }
        public System.DateTime FechaSiembra { get; set; }
        public Nullable<int> DensidadPlantas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AplicacionFertilizante> AplicacionFertilizantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AplicacionPlaga> AplicacionPlagas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionTarea> AsignacionTareas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cosecha> Cosechas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gastoes { get; set; }
        public virtual Lote Lote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Riego> Riegoes { get; set; }
        public virtual Temporada Temporada { get; set; }
        public virtual Variedad Variedad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsoMaquinaria> UsoMaquinarias { get; set; }
    }
}
