//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriculturaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsoMaquinaria
    {
        public int IdSiembra { get; set; }
        public int IdMaquinaria { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Horas { get; set; }
    
        public virtual Maquinaria Maquinaria { get; set; }
        public virtual Siembra Siembra { get; set; }
    }
}
